### ISSUE TITLE
Publish Skill to German Alexa Skill Store

### ISSUE THREAD

**Issue by floooooooooo** [thorpelawrence/alexa-spotify-connect#14]

**Comment by thorpelawrence** [comment]
I'd be happy to do that, unfortunately, I wouldn't be able to translate it myself, so if you would like it translated feel free to submit a pull request so I can set up a new branch.

**Comment by floooooooooo** [comment]
https://github.com/thorpelawrence/alexa-spotify-connect/pull/15
Everything should be translated to German now

**Comment by thorpelawrence** [comment]
Slight change of plans:
Instead of publishing as a separate branch/endpoint, I'm working on adding proper i18n support so that other languages can be added in the future, which should also help to keep server use lower.
Hopefully, this will be working within a few days.

**Comment by thorpelawrence** [comment]
I've added i18n support now, there is a locale file in [de-DE.json](https://github.com/thorpelawrence/alexa-spotify-connect/blob/i18n/locales/en-GB.json), I added a few of the translations to that but didn't get around to finishing them, feel free to update/check them.

**Comment by thorpelawrence** [comment]
Still to do:

- [ ] Fix issue with i18n test
- [ ] Find a way to use i18n with slots/utterances

**Comment by thorpelawrence** [comment]
Found a way to handle locales for utterances, it seems that there is a lot more utterances generated with [de-DE.json](https://github.com/thorpelawrence/alexa-spotify-connect/blob/i18n/skill/locales/de-DE.json) but seems to be working alright.
I will have a look over everything to check it then submit for certification tomorrow; feel free to check the utterance generation with `yarn utterances-i18n` and let me know if there are any issues. Hopefully, that will allow for easy changes for other languages if necessary.

**Comment by thorpelawrence** [comment]
@floooooooooo Thanks for all your help and PRs, the last thing before publishing would be some translation of the store (name, description, sample phrases), and I hope to get it submitted to Amazon for their approval tomorrow.

![screenshot_20180214_224356](https://user-images.githubusercontent.com/9198615/36232157-8d657d8e-11d8-11e8-925c-d81921a2c8da.png)
---
![screenshot_20180214_224111](https://user-images.githubusercontent.com/9198615/36232162-97dd5ae8-11d8-11e8-8c03-a165a1fac758.png)

**Comment by floooooooooo** [comment]
No Problem ;)
Name: Connect Control für Spotify
Invocation Name can stay the same

Description:
Steuere deine Spotify Connect Geräte mit Alexa

Source code: https://github.com/thorpelawrence/alexa-spotify-connect

Für die Nutzung auf einigen Geräte kann ein Spotify Premium-Konto erforderlich sein

HAFTUNGSAUSSCHLUSS:
Dieses Produkt ist in keiner Weise von Spotify bestätigt, zertifiziert oder anderweitig genehmigt. Spotify ist ein eingetragenes Markenzeichen der Spotify Group.

Samples phrases:
- "Alexa, sage Connect Control spiel' Musik auf dem Gerät 2"
- "Alexa, sage Connect Control pause"
- "Alexa, sage Connect Control übertrage Wiedergabe auf das Gerät 3"

**Comment by thorpelawrence** [comment]
@floooooooooo Thanks again for all your help, I've submitted to the Amazon store, just waiting for approval now which could take a few days.
