### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by John-d-oh** [thorpelawrence/alexa-spotify-connect#3]
Hi there! thanks so much for writing this wonderful skill! I was so happy to find it. I wasn't using the Alexa cause it was so useless without being able to control my home speakers.
I tried my hand at adding a volume setting skill - I'm sure it needs some refining, but should work.  Hope this is helpful for you and other users.

**Comment by thorpelawrence** [comment]
Hi, thanks for your interest
I'd be happy to accept a pull request for the volume control if you want to open one up with your changes
