### ISSUE TITLE
Add support for Spanish (Spain)

### ISSUE THREAD

**Issue by mediocaballero** [thorpelawrence/alexa-spotify-connect#33]
This looks great! I'm very interested in using this in my spanish account. :-)

If I provide a pull request with the internationalization files (as per the readme instructions), would you update it and add it to the spanish market, please?

**Comment by thorpelawrence** [comment]
Hi, that would be great!

I will definitely try to publish it, but be aware though, that in the past there have been a few issues on adding new languages where it takes a long time to release, but hopefully these should not happen.

**Comment by mediocaballero** [comment]
Great, thanks! Will send a pull request when it's ready.
BTW, is the locales file in english available somewhere (the one to place in skill/locales with the intents)? It'd be easier for me to translate them from English...
Thanks!

**Comment by thorpelawrence** [comment]
I think you mean part 2 of deployment, if you try that it generates the possible responses, then you can translate some of those to fit the language best

**Comment by thorpelawrence** [comment]
Otherwise, every intent is listed in `connect.js` for `app.intent` functions

**Comment by thorpelawrence** [comment]
Thanks a lot for submitting this!
I've merged it into master (that's what is used in production), so I will try to submit the skill to the Spanish store, expect a few weeks if it goes fine.

**Comment by thorpelawrence** [comment]
Hi @mediocaballero, one last thing I forgot, would you be able to supply the information from https://github.com/thorpelawrence/alexa-spotify-connect/issues/14#issuecomment-365770234 so that I can publish it correctly?

Thanks again

**Comment by mediocaballero** [comment]
Sure! Thanks to you for the quick responses and for this open source project!

Name: Connect Control para Spotify
Invocation Name: connect control

Description:
Controla tus dispositivos de Spotify Connect con Alexa

Código fuente: https://github.com/thorpelawrence/alexa-spotify-connect

El uso en algunos dispositivos puede requerir una cuenta Premium de Spotify

Exención de responsabilidad:
Este producto no está avalado, certificado o aprobado por Spotify. Spotify es una marca registrada del Grupo Spotify.

Example phrases:

"Alexa, dile a Connect Control que reproduzca música en el dispositivo 2"
"Alexa, dile a Connect Control que ponga la pausa"
"Alexa, dile a Connect Control que transfiera la reproducción al dispositivo 3"

**Comment by thorpelawrence** [comment]
Thanks again!

Submitted tonight, hopefully it will be approved soon.

**Comment by mediocaballero** [comment]
Great, thanks!
Will try to keep an eye on it to give it a try when it's up, but please drop a comment here if you get the notice that it's published so I get the notification, please 👍

**Comment by dgonzalo-sgt** [comment]
Has there been any news? It's not in the spanish store yet... did they reject the skill?

**Comment by mediocaballero** [comment]
Has there been any news? It's not in the spanish store yet... did they reject the skill?

**Comment by thorpelawrence** [comment]
Hi there,

Sorry for not updating anything, I've been very busy recently

They rejected but I've made some changes and it has been resubmitted so waiting to hear back from them

**Comment by mediocaballero** [comment]
No problem, thanks for the update! 👍

**Comment by thorpelawrence** [comment]
Sorry for the long delays, but it has finally been accepted, it should be available ASAP

Thanks again for the contribution

**Comment by mediocaballero** [comment]
Great! I'm seeing it as availabe right now :-)
https://www.amazon.es/Lawrence-Thorpe-Connect-Control-Spotify/dp/B074KFNWFD
Will give it a try as soon as possible and report back! 👍 

Thanks!
