### ISSUE TITLE
Rename connect control

### ISSUE THREAD

**Issue by rpostulart** [thorpelawrence/alexa-spotify-connect#6]
Is connect control a standard value which you can't change? Otherwise it would be handy to call it spotify connect. So Alexa, ask spotify connect ....

And would it also possible to ask connect control to play song X?

**Comment by thorpelawrence** [comment]
I originally tried to make the name just *Connect*, but Amazon did not approve it as it was not unique enough, so they suggest 2 word names.

I would consider changing the name if I got enough feedback but it would require recreating the skill on Amazon's side, so it would have to be reapproved as a brand new skill so is quite a lot of effort and time.

**Comment by rpostulart** [comment]
I do understand. I will get used to it :)

I saw stop control is not working. Is there a way I can help you with this code? Because it is real promising.

I am not an expert developer, but I can read and test.

**Comment by thorpelawrence** [comment]
General testing is always useful, if you see any problems please let me know
Otherwise feel free to add anything you want and if I think it makes sense I will add it to the project
