### ISSUE TITLE
Alexa skill deactivated connect control for Spotify

### ISSUE THREAD

**Issue by lexnared** [thorpelawrence/alexa-spotify-connect#60]
It's possible that's the connect control skill for Spotify was deactivated?
It's not longer available in the skill search.

I used the echo dot in Germany.

**Comment by thorpelawrence** [comment]
Hi there,

It looks like it was removed by Amazon because they were having issues testing it without a premium account. I have resubmitted the skill to try to get approval again

Thanks

**Comment by thorpelawrence** [comment]
Looks like the skill was approved, should be back in the German store now!
