### ISSUE TITLE
Device list

### ISSUE THREAD

**Issue by colder1989** [thorpelawrence/alexa-spotify-connect#62]
hi, when i say "Alexa, ask Connect control to play on device 1", Alexa answers me by telling me the list of devices. I laugh again dipositive 1 and finally reproduces. How come? 
thanks

**Comment by thorpelawrence** [comment]
Hi there, you might be able to ask it to list devices first and then play, although it should find devices when you try so I'm not sure why that is happening, but it should keep that list for a short amount of time (around 10 minutes)

Hope this helps
