### ISSUE TITLE
cannot make this work

### ISSUE THREAD

**Issue by lch48a** [thorpelawrence/alexa-spotify-connect#7]
Hello, I tried different commands, but none seems to work. 
Upon "Alexa ask Connect Control to list devices"
I get something like "I don't see anything to connect. Go to your Alexa app".

**Comment by thorpelawrence** [comment]
Hi there, the problem might be that the Spotify account login is having some problems, if you disable and re-enable the skill to log in to the account again, that should make sure the details are up to date.

**Comment by lch48a** [comment]
Thanks. It now connects!  
How do you ask connect control:
- to play a specific playlist?
- to skip or play next track in playlist?
I tried several ways, but with no success.

**Comment by thorpelawrence** [comment]
Unfortunately, the skill can't do this yet, I would suggest for now that you start playback with regular Spotify, then you could control devices with this skill

**Comment by thorpelawrence** [comment]
Skip/next should work, but you would need to start playback on another device or using the default media controls in Alexa, rather than this skill
