### ISSUE TITLE
Support more utterances for switching devices

### ISSUE THREAD

**Issue by mattrossman** [thorpelawrence/alexa-spotify-connect#71]
The first two phrases that came to my mind when trying to use this skill:

"Ask connect control to **switch to** my Echo dot"
"Ask connect control to **use** my Echo dot"

Neither of these accomplished what I intended, instead they made Alexa tell me the name of the current song. I believe these phrasings should be supported for `DeviceTransferIntent`

Some other phrasings that people may use:
"Ask connect control to **swap to** my Echo dot"
"Ask connect control to **move to** my Echo dot"

**Comment by thorpelawrence** [comment]
Added to English, English US, and English CA, and submitted to Amazon for approval - bare in mind it may take up to a month for them to approve it

Thanks for the suggestions!

**Comment by thorpelawrence** [comment]
Looks like as it was such a small change I was able to update the skill live, so should be good to go with the new phrases

**Comment by mattrossman** [comment]
Awesome, it's working great for me now!
