### ISSUE TITLE
Spotify Log In Problems

### ISSUE THREAD

**Issue by leti3689** [thorpelawrence/alexa-spotify-connect#75]
Hello Thorpelawrence,

I wanted to try this Alexa skill, downloaded it connected my spotify and now my Password has been changed?

**Comment by thorpelawrence** [comment]
Hey, so am I right in thinking that you have changed your password, and you want to re-link the skill to your account?

**Comment by leti3689** [comment]
No I canˋt log into my Spotify anymore

**Comment by thorpelawrence** [comment]
In that case maybe you can [reset your password on Spotify](https://www.spotify.com/uk/password-reset/) and try to link again?
