### ISSUE TITLE
More precise volume control

### ISSUE THREAD

**Issue by visadb** [thorpelawrence/alexa-spotify-connect#80]
My sound system is so powerful that the usable volume range is 1-15%, so currently I can set three volume levels:
`0` = 0%: mute
`1` = 10%: quite loud
`2` = 20%: waaaaay too loud

So basically I would like to revert the part of https://github.com/thorpelawrence/alexa-spotify-connect/pull/5 that changes the volume range from 0-99 to 0-10.

**Comment by thorpelawrence** [comment]
Hi @visadb, interesting point

Some of the options I could think about for solving this are

- a value >10 would be percentage (not sure this would work for you)
- an extra intent including the word percentage that allows more specific numbers
- specify with decimal e.g. **set volume to zero point one five**

I'm not really sure what the best approach to do this would be, as reverting the change from near the start would be quite breaking of current use cases

**Comment by visadb** [comment]
@thorpelawrence I think the extra intent with the word percent would probably be best. That would not change the behaviour of the current 1-10 volume intent and then I would be able to set volumes between 1-10% which would not be possible with the first option.

The decimal option would be more or less equivalent to the percent intent option but IMHO would be less natural to use, and would be a little awkward to implement code-wise as well.

**Comment by thorpelawrence** [comment]
@visadb I agree that is probably the best option here then, do you think you might be able to implement it and open a pull request? As otherwise I have been quite busy unfortunately so not sure when I would be able to get around to implementing it

**Comment by visadb** [comment]
@thorpelawrence I'll try to find the time to implement the volume percent intent and open a pull request.

**Comment by visadb** [comment]
PR #81 solved this issue for me. Thank you for the quick review, merge and deployment, @thorpelawrence!
