### ISSUE TITLE
Can't connect to my LG TV

### ISSUE THREAD

**Issue by jonnyapps** [thorpelawrence/alexa-spotify-connect#90]
My LG TV shows in Spotify and works fine, but I can't connect to it using this skill. It may be because it has a stupid (and non changeable) name: [LG] WebOS TV OLED55PLA.

I've tried making a routine with that exact name but no dice.

Thanks very much for the excellent work on this app.

Best wishes.
Jon

**Comment by jonnyapps** [comment]
Solved this myself by just saying 'LG' and not typing the whole TV name and hard brackets.

**Comment by thorpelawrence** [comment]
Good to hear you got it working, glad the fuzzy matching worked for that case
