### ISSUE TITLE
Spotify Free +Alexa 

### ISSUE THREAD

**Issue by avbprog66** [thorpelawrence/alexa-spotify-connect#97]
Make it possible to listen to Spotify Free with Alexa on Denon receivers!  PLEASE!

**Comment by thorpelawrence** [comment]
Hi there, I'm not sure if Spotify themselves support that, but for this Alexa skill specifically premium is required

**Comment by avbprog66** [comment]
> Hi there, I'm not sure if Spotify themselves support that, but for this Alexa skill specifically premium is required

Hello!  Yes, I am aware that a Premium subscription is required.  For example, previously, Denon receivers also did not support streaming without a Spotify subscription, but now this is implemented.  Based on this, I thought that here the craftsmen will be able to implement this.  Yes, while Spotify does not have hifi sound quality, I don’t see any reason to pay for, relatively speaking, mp3 quality.

**Comment by thorpelawrence** [comment]
Unfortunately, I have no control over what Spotify provides, as this service just interacts with the public API they provide. I don't have either of those sound systems so no way to test it, but most likely if it can't be done through a phone/computer then this skill won't be able to do so either I'm afraid

**Comment by avbprog66** [comment]
> Unfortunately, I have no control over what Spotify provides, as this service just interacts with the public API they provide. I don't have either of those sound systems so no way to test it, but most likely if it can't be done through a phone/computer then this skill won't be able to do so either I'm afraid

Here's the trouble.  It is a pity that all this was not initially implemented by Amazon.  And Spotify doesn't care about its users.  Thanks for answers.
